package writer

import (
	"fmt"
	"os"
	"path/filepath"
)

// GenerateDuckDBArtifacts creates DuckDB ingest SQL and helper queries.
// Called from Writer.Close() when duckdb/parquet mode enabled.
// We keep jsonl as ground truth and let DuckDB read_json/read_parquet natively — fastest in Go + queryable.
func (w *Writer) GenerateDuckDBArtifacts() error {
	// Always generate SQL helper even for jsonl-only, if user requested duckdb
	dir := w.baseDir
	// ingest.sql: creates a persistent DuckDB file from jsonl + parquet
	sqlPath := filepath.Join(dir, "ingest.duckdb.sql")
	sql := fmt.Sprintf(`-- Auto-generated by discord-scraper-go
-- Usage: duckdb %s/output.duckdb < ingest.duckdb.sql
-- Or: duckdb -c "SELECT * FROM read_json('%s/**/*.jsonl', auto_detect=true, ignore_errors=true) LIMIT 5"

-- Create DuckDB file with all messages (JSONL)
-- Requires duckdb >=0.8
PRAGMA threads=8;
PRAGMA memory_limit='2GB';

DROP TABLE IF EXISTS messages;
CREATE TABLE messages AS
SELECT
  id::VARCHAR AS id,
  channel_id::VARCHAR AS channel_id,
  author.id::VARCHAR AS author_id,
  author.username::VARCHAR AS author_username,
  content::VARCHAR AS content,
  timestamp::TIMESTAMPTZ AS timestamp,
  edited_timestamp::TIMESTAMPTZ AS edited_timestamp,
  pinned::BOOLEAN AS pinned,
  type::INTEGER AS type,
  attachments AS attachments,
  embeds AS embeds,
  reactions AS reactions
FROM read_json('%s/**/*.jsonl', auto_detect=true, ignore_errors=true, maximum_object_size=16777216);

-- Secondary: if you used --format parquet
-- CREATE TABLE messages_parquet AS SELECT * FROM read_parquet('%s/**/*.parquet');

-- Useful indexes
CREATE INDEX IF NOT EXISTS idx_messages_channel ON messages(channel_id);
CREATE INDEX IF NOT EXISTS idx_messages_author ON messages(author_id);
CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON messages(timestamp);

-- Example queries (uncomment):
-- SELECT channel_id, count(*) AS cnt FROM messages GROUP BY channel_id ORDER BY cnt DESC;
-- SELECT author_username, count(*) FROM messages GROUP BY author_username ORDER BY count(*) DESC LIMIT 20;
-- SELECT * FROM messages WHERE content ILIKE '%%hello%%' LIMIT 10;
-- SELECT date_trunc('day', timestamp) AS day, count(*) FROM messages GROUP BY day ORDER BY day;

`, dir, dir, dir, dir)

	if err := os.WriteFile(sqlPath, []byte(sql), 0o644); err != nil {
		return err
	}

	// Also write a helper shell script
	shPath := filepath.Join(dir, "query.sh")
	sh := fmt.Sprintf(`#!/usr/bin/env bash
# Helper: query without creating a persistent DB
# Requires duckdb CLI: https://duckdb.org/docs/installation/
set -e
DB="%s/output.duckdb"
SQL="%s/ingest.duckdb.sql"
if command -v duckdb >/dev/null 2>&1; then
  echo "Creating $DB from JSONL (takes ~seconds per 100M rows)..."
  duckdb "$DB" < "$SQL"
  echo "Done. Query example:"
  echo "  duckdb $DB -c \"SELECT channel_id, count(*) FROM messages GROUP BY channel_id ORDER BY count(*) DESC LIMIT 20\""
else
  echo "duckdb not found. Install: curl https://install.duckdb.org | sh"
  echo "Or query directly without DB: duckdb -c \"SELECT * FROM read_json('%s/**/*.jsonl', auto_detect=true) LIMIT 5\""
fi
`, dir, dir, dir)
	_ = os.WriteFile(shPath, []byte(sh), 0o755)

	// Try to actually run duckdb if available and format was duckdb (non-fatal)
	// We don't auto-run to avoid surprising long ingest; user runs query.sh or ingest.sql manually.
	return nil
}

// Parquet helper: schema for floor writer (used when format=parquet)
type ParquetRow struct {
	ID              string `parquet:"name=id, type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY"`
	ChannelID       string `parquet:"name=channel_id, type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY"`
	GuildID         string `parquet:"name=guild_id, type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY"`
	AuthorID        string `parquet:"name=author_id, type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY"`
	AuthorUsername  string `parquet:"name=author_username, type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY"`
	Content         string `parquet:"name=content, type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY"`
	Timestamp       string `parquet:"name=timestamp, type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY"`
	EditedTimestamp string `parquet:"name=edited_timestamp, type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY"`
	Pinned          bool   `parquet:"name=pinned, type=BOOLEAN"`
	Type            int32  `parquet:"name=type, type=INT32"`
	HasAttachments  bool   `parquet:"name=has_attachments, type=BOOLEAN"`
	HasEmbeds       bool   `parquet:"name=has_embeds, type=BOOLEAN"`
}
